/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.pruebas;

import Ventanas.ConexionBD;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick Daniel
 */
public class Ingresar extends javax.swing.JFrame {
    ConexionBD con = new ConexionBD();
    Connection cn = con.conexion();
    /**
     * Creates new form Ingresar
     */
    public Ingresar() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imagen = new ImageIcon("src/imagenes/computer_green.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(icono);
        jLabel2.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 180, 150));
        getContentPane().add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 100, -1));

        jButton1.setText("Registrarse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 170, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtCuenta.getText().length() == 0){
            JOptionPane.showMessageDialog(null,"No has insertado tu numero de cuenta");
        }
        else{
            String nombre = null;
            String PC = null;
            int sesion = 0;
            int computadora = 0;
            Date date = new Date();
            DateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
            String cuenta = txtCuenta.getText();
            String sql = "SELECT * FROM alumnos WHERE cuenta = " + cuenta;
            String hora = hourFormat.format(date);
            String fecha = dateFormat.format(date);
            PreparedStatement pps;
            Statement st;
            ResultSet rs;
            try {
                st = cn.createStatement();
                rs = st.executeQuery(sql);
                if(rs.next()){
                    nombre = rs.getString(3) + " " + rs.getString(4) + " " + rs.getString(2) ;
                    sql = "SELECT * FROM control_sesion WHERE cuenta = " + cuenta;
                    st = cn.createStatement();
                    rs = st.executeQuery(sql);
                    if(rs.next() && rs.getString(4).equals("00:00:00")){
                        computadora = rs.getInt(7);
                        sql = "SELECT * FROM computadoras WHERE id_computadora = " + computadora;
                        st = cn.createStatement();
                        rs = st.executeQuery(sql);
                        while(rs.next()){
                            PC = rs.getString(2);
                        }
                        hora = hourFormat.format(date);
                        pps = cn.prepareStatement("UPDATE computadoras SET estado = 'Disponible' WHERE id_computadora = " + computadora);
                        pps.executeUpdate();
                        procedimiento(computadora,"Disponible");
                        pps = cn.prepareStatement("UPDATE control_sesion SET hora_final = '" + hora + "' WHERE id_computadora = " + computadora);
                        pps.executeUpdate();
                        JOptionPane.showMessageDialog(null,"Hasta luego: " + nombre + "\n PC asignada: " + PC + "\n Hora final: " + hora);    
                    }
                    else{
                        sql = "SELECT * FROM control_sesion";
                        st = cn.createStatement();
                        rs = st.executeQuery(sql);
                        if(rs.last()){
                            sesion = rs.getInt(1);
                        }
                        sql = "SELECT * FROM computadoras";
                        st = cn.createStatement();
                        rs = st.executeQuery(sql);
                        while(rs.next()){
                            if(rs.getString(3).equals("Disponible")){
                                computadora = rs.getInt(1);
                                PC = rs.getString(2);
                                break;
                            }
                        }
                        pps = cn.prepareStatement("UPDATE computadoras SET estado = 'Ocupado' WHERE id_computadora = " + computadora);
                        pps.executeUpdate();
                        procedimiento(computadora,"Ocupado");
                        pps = cn.prepareStatement("INSERT INTO control_sesion (id_sesion,fecha,hora_inicio,hora_final,semestre,cuenta,id_computadora) VALUES (?,?,?,?,?,?,?)");
                        pps.setInt(1,sesion + 1);
                        pps.setString(2,fecha);
                        pps.setString(3,hora);
                        pps.setString(4,"24:00:00");
                        pps.setString(5,"2018B");
                        pps.setString(6,cuenta);
                        pps.setInt(7,computadora);
                        pps.executeUpdate();
                        JOptionPane.showMessageDialog(null,"Bienvenido/a: " + nombre + "\n PC asignada: " + PC + "\n Hora inicio: " + hora);    
                    }                    
                }
                else{
                    JOptionPane.showMessageDialog(null,"El alumno no existe");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Ingresar.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void procedimiento(int a,String estado){
        ImageIcon imagen = null;
        Icon icono = null;
        if(estado.equals("Disponible")){
            imagen = new ImageIcon("src/imagenes/computer_green.png");
            icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(), Image.SCALE_DEFAULT));    
        }
        if(estado.equals("Ocupado")){
            imagen = new ImageIcon("src/imagenes/computer_red.png");
            icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(), Image.SCALE_DEFAULT));    
        }
        switch (a){
            case 100:
                jLabel1.setIcon(icono);    
                break;
            case 200:
                jLabel2.setIcon(icono);
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCuenta;
    // End of variables declaration//GEN-END:variables
}
